### ISSUE TITLE
Issues with receiving segmentation mask

### ISSUE THREAD

**Issue by heorhiikalaichev** [FelixCaae/CrowdSAM#5]
Thanks a lot for your job.

I have an issue with receiving segmentation masks during inference.
I ran this command `python tools/test.py --config_file ./configs/crowdhuman.yaml --visualize --mode seg`, but there are only bboxes in result images.

![0](https://github.com/user-attachments/assets/5872442a-e1f9-4b8a-9fa0-b84c24101e53)

**Comment by FelixCaae** [comment]
Hello, I have updated the code and add a demo.py in tools. You can use 'python tools/demo.py -i target_directory' to test on a directory of images! Also I have fixed the issue of not receiving masks.
